version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../grpc-server:/var/www/html/server
      - ../grpc-client:/var/www/html/client
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: dockerfile
    image: php-gprc
    volumes:
      - ../grpc-server:/var/www/html/server
      - ../grpc-client:/var/www/html/client
